minio:
  mode: standalone
  replicas: 1

  rootUser: minioadmin
  rootPassword: minioadmin

  persistence:
    size: 10Gi

  resources:
    requests:
      memory: 512Mi

  buckets:
    - name: clickhouse
      policy: none
      purge: false

cognative:
  clickhouse:
    extra:
      config:
        minio.xml: |
          <clickhouse>
            <storage_configuration>
              <disks>
                <s3>
                  <type>s3</type>
                  <endpoint>http://cognative-s3-minio:9000/clickhouse/clickhouse</endpoint>
                  <access_key_id>minioadmin</access_key_id>
                  <secret_access_key>minioadmin</secret_access_key>
                  <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path>
                </s3>
                <s3_cache>
                  <type>cache</type>
                  <disk>s3</disk>
                  <path>/var/lib/clickhouse/disks/s3_cache/</path>
                  <max_size>10Gi</max_size>
                  <cache_on_write_operations>1</cache_on_write_operations>
                </s3_cache>
              </disks>
              <policies>
                <default>
                  <volumes>
                    <hot>
                      <disk>default</disk>
                    </hot>
                    <cold>
                      <disk>s3_cache</disk>
                      <prefer_not_to_merge>false</prefer_not_to_merge>
                      <perform_ttl_move_on_insert>false</perform_ttl_move_on_insert>
                    </cold>
                  </volumes>
                  <move_factor>0.2</move_factor>
                </default>
              </policies>
            </storage_configuration>
          </clickhouse>
        zero-copy.xml: |
          <clickhouse>
            <merge_tree>
              <allow_remote_fs_zero_copy_replication>false</allow_remote_fs_zero_copy_replication>
            </merge_tree>
          </clickhouse>
