volumes:
  minio_data: {}
  clickhouse_data: {}
  grafana_data: {}

services:
  minio:
    image: quay.io/minio/minio:latest # amd64 + arm64
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: mc ready local || exit 1
      interval: 10s
      timeout: 5s
    volumes:
      - minio_data:/data

  clickhouse:
    depends_on:
      minio:
        condition: service_healthy
    image: clickhouse/clickhouse-server:24.4 # amd64 + arm64
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./docker/clickhouse:/etc/clickhouse-server/config.d
      - clickhouse_data:/var/lib/clickhouse

  collector:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: otel/opentelemetry-collector-contrib:0.100.0 # amd64 + arm64
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./docker/collector:/etc/otelcol-contrib

  # cluster-agent: {}
  # host-agent: {}

  grafana:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: grafana/grafana-oss:10.4.2 # amd64 + arm64
    environment:
      GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource"
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
