name: cognative

volumes:
  minio_data: {}
  clickhouse_data: {}
  grafana_data: {}

services:
  #==
  # Supporting Services
  #==

  traefik:
    image: traefik:v3.3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/opt/traefik/etc
    command:
      - --configFile=/opt/traefik/etc/config.yaml
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.cognative.work`)"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  minio:
    image: quay.io/minio/minio:latest # amd64 + arm64
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: mc ready local || exit 1
      interval: 10s
      timeout: 5s
    volumes:
      - minio_data:/data
    labels:
      - "traefik.http.routers.minio.rule=Host(`minio.local.cognative.work`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"

  minio-buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/clickhouse;
      exit 0;
      "

  #==
  # Core Services
  #==

  clickhouse:
    depends_on:
      minio:
        condition: service_healthy
      minio-buckets:
        condition: service_completed_successfully
    image: clickhouse/clickhouse-server:24.12 # amd64 + arm64
    environment:
      CLICKHOUSE_DB: otel
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./clickhouse:/etc/clickhouse-server/config.d
      - clickhouse_data:/var/lib/clickhouse

  collector:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: otel/opentelemetry-collector-contrib:0.119.0 # amd64 + arm64
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./collector:/etc/otelcol-contrib
    labels:
      - "traefik.http.routers.collector.rule=Host(`collector.local.cognative.work`)"
      - "traefik.http.routers.collector.service=collector"
      - "traefik.http.services.collector.loadbalancer.server.port=4318"

  # cluster-agent: {}
  # host-agent: {}

  grafana:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: grafana/grafana-oss:11.5.1 # amd64 + arm64
    environment:
      GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource"
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.cognative.work`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
