clickhouse:
  enabled: true

  auth:
    username: clickhouse
    password: clickhouse

  zookeeper:
    enabled: true

collector:
  enabled: true

  mode: "deployment"
  replicaCount: 2

  config:
    processors:
      batch:
        timeout: 5s
        send_batch_size: 100000

    exporters:
      clickhouse:
        endpoint: tcp://{{ .Release.Name }}-clickhouse:9000?dial_timeout=10s&compress=lz4
        database: otel
        username: clickhouse
        password: clickhouse
        ttl: 72h
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 5s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      pipelines:
        logs:
          exporters:
            - clickhouse
        metrics:
          exporters:
            - clickhouse
        traces:
          exporters:
            - clickhouse

grafana:
  enabled: true

  replicas: 1

  adminUser: admin
  adminPassword: admin

  plugins:
    - grafana-clickhouse-datasource

  datasources:
    "datasources.yaml":
      apiVersion: 1
      datasources:
        - name: ClickHouse
          type: grafana-clickhouse-datasource
          jsonData:
            defaultDatabase: default
            port: 9000
            host: "{{ .Release.Name }}-clickhouse"
            username: clickhouse
            secure: false
            protocol: native
            logs:
              defaultDatabase: otel
              defaultTable: otel_logs
              otelEnabled: true
              otelVersion: latest
            traces:
              defaultDatabase: otel
              defaultTable: otel_traces
              otelEnabled: true
              otelVersion: latest
              durationUnit: milliseconds
          secureJsonData:
            password: clickhouse
