name: Ensure code style

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    name: Ensure code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: npm install

      - name: Ensure code style
        run: npm run format:check

      - name: Ensure licensing
        run: npm run legal:check
